version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: "instagramm_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: core
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      # Используем имя сервиса базы – "postgres"
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5432"
      POSTGRES_DB: "instagramm_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      ENV: "local"
      CONFIG_PATH: "./configs/local.yaml"
    ports:
      - "8080:8080"
    command: ["./app"]

volumes:
  pgdata: